services:
  - type: web
    name: si-ai-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 10000
      - key: TF_CPP_MIN_LOG_LEVEL
        value: "2"
      - key: CUDA_VISIBLE_DEVICES
        value: ""